// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package postgres

import (
	"time"
)

type User struct {
	ID      int64     `json:"id"`
	Name    string    `json:"name"`
	Surname string    `json:"surname"`
	Contact string    `json:"contact"`
	Address string    `json:"address"`
	Birth   time.Time `json:"birth"`
	Cpf     string    `json:"cpf"`
}
