// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package postgres

import (
	"time"
)

type User struct {
	ID      int64
	Name    string
	Surname string
	Contact string
	Address string
	Birth   time.Time
	Cpf     string
}
